server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          client-auth-code:
            provider: demo
            client-id: '000000'
            client-secret: '999999'
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized"
            scope: read,write
          client-client-creds:
            provider: demo
            client-id: '000000'
            client-secret: '999999'
            authorization-grant-type: client_credentials
            scope: read,write
          client-password:
            provider: demo
            client-id: '000000'
            client-secret: '999999'
            authorization-grant-type: password
            scope: read,write
        provider:
          demo:
            authorization-uri: http://localhost:9001/oauth/authorize
            token-uri: http://localhost:9001/oauth/token
            user-info-uri: http://localhost:9001/auth/user/info
            user-info-authentication-method: header
            user-name-attribute: username
# 资源地址
resource:
  base-uri: http://localhost:8081
#  base-uri: http://localhost:9001/auth/user/info