server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          auth-server:
            provider: demo-provider
            client-id: '000000'
            client-secret: '999999'
            scope: read, write
            client-authentication-method: basic
            authorization-grant-type: password
        #            authorization-grant-type: authorization_code
        #            scope: message.read,message.write
        #            authorization-grant-type: client_credentials
        #            scope: message.read,message.write
        provider:
          demo-provider:
            authorization-uri: http://localhost:9001/oauth/authorize
            token-uri: http://localhost:9001/oauth/token
      #            user-info-uri: http://172.17.0.1:9001/oauth/v1/userinfo